return {
	"ThePrimeagen/harpoon",
	keys = {
		{
			"<leader>a",
			function()
				require("harpoon.mark").add_file()
			end,
		},
		{
			"<leader>e", -- NOTE: <C-e> conflicts with lspsaga
			function()
				require("harpoon.ui").toggle_quick_menu()
			end,
		},
		{
			"<leader>a",
			function()
				require("harpoon.ui").nav_file(1)
			end,
		},
		{
			"<leader>s",
			function()
				require("harpoon.ui").nav_file(2)
			end,
		},
		{
			"<leader>d",
			function()
				require("harpoon.ui").nav_file(3)
			end,
		},
		{
			"<leader>f",
			function()
				require("harpoon.ui").nav_file(4)
			end,
		},
	},
}
